### ISSUE TITLE
Illegal Quarg outfit

### ISSUE THREAD

**Issue by Drasli-Tana** [mathwhiz1212/A-Coalition-At-War#6]
**Describe the bug**
When landing on the two east-most Quarg systems in the gegno space with Quarg outfit, you get arrested.

**To Reproduce**
1: Start on the Quarg side
2: Buy a quarg outfit (tested with *intrusion coutermeasure* (free by the way))
3: Land on  a planet in either Aleit or Actannka system

**Expected behavior**
As any other quarg system, they should not arrest you

**Desktop (please complete the following information):**
 - OS: Ubuntu23.10

**Additional context**
[Drasli Tana 2.txt](https://github.com/mathwhiz1212/A-Coalition-At-War/files/13733166/Drasli.Tana.2.txt)

A save file one jump away from a problematic system

**Comment by mathwhiz1212** [comment]
@Drasli-Tana Thank you for reporting the bug. I'll look into this.

**Comment by mathwhiz1212** [comment]
@Drasli-Tana Have you tested any of the other new species' planets to see if it's an issue there?

**Comment by mathwhiz1212** [comment]
Nevermind. I found the problem. The new versions of Endless Sky have a few different governments for the Quarg depending on the location behind the scenes.

**Comment by mathwhiz1212** [comment]
@Drasli-Tana Try following the instructions here: https://github.com/mathwhiz1212/A-Coalition-At-War/releases/tag/v0.10.4a

**Comment by mathwhiz1212** [comment]
@Drasli-Tana Excellent!
