### ISSUE TITLE
Plugin not showing up in, Preferences > Plugins, on main menu.

### ISSUE THREAD

**Issue by titaniumcar** [mathwhiz1212/A-Coalition-At-War#7]
**The Issue**
So I followed the instructions on downloading the plugin, going to .local > share > endless-sky > plugins, and extracting the zip file there. Then I restarted Endless Sky and couldn't find the plugin. I checked the plugin folder through Endless Sky and the extracted file was there.

**To Reproduce**
I don't know if its just me with this problem but I followed the exact instructions on downloading the plugin.
1. Download Zip file from github, v10.4.2
2. Extract to .local > share > endless-sky > plugins
3. Restart Endless Sky
4. Go to Preferences > Plugins, and I couldn't find the plugin.

**Expected behavior**
I wanted to see the plugin there and play the game with it.

**Screenshots**
![image](https://github.com/mathwhiz1212/A-Coalition-At-War/assets/157324972/99020b25-5045-434c-91af-897f7a93dd00)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Brave Browser
 - Version 22.04

**Additional context**
There might be something I'm missing here, I don't know what?

**Comment by mathwhiz1212** [comment]
What version of Endless Sky are you using? 

Also  use @mathwhiz1212 in replies, or I won't see it for a while.

**Comment by mathwhiz1212** [comment]
@titaniumcar Thanks for reporting this bug! It should be fixed now if you download the .zip file again.

Thanks for using the plugin!

I zipped the directory above the plugin on accident, it should have the right structure now.

**Comment by mathwhiz1212** [comment]
Please re-open the issue if you encounter any more problems.
